# Generated by Django 4.2.16 on 2025-06-04 19:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maintenance", "0007_alter_maintenanceplan_name_and_more"),
        ("users", "0002_alter_dataconsent_consent_type"),
        ("vehicles", "0003_alter_vehiclehistory_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_done", models.TextField(verbose_name="Work Performed")),
                (
                    "date_performed",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date/Time of Service",
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        verbose_name="Vehicle Mileage at Service"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Additional Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scheduled_maintenance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_records",
                        to="maintenance.scheduledmaintenance",
                        verbose_name="Scheduled Maintenance",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_maintenance",
                        to="users.user",
                        verbose_name="Technician",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_history",
                        to="vehicles.vehicle",
                        verbose_name="Vehicle (VIN)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Record",
                "verbose_name_plural": "Maintenance Records",
                "ordering": ["-date_performed"],
            },
        ),
        migrations.CreateModel(
            name="PartUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Cost per Unit",
                    ),
                ),
                (
                    "maintenance_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts_used",
                        to="maintenance_history.maintenancerecord",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="maintenance.part",
                    ),
                ),
            ],
            options={
                "verbose_name": "Part Usage",
                "verbose_name_plural": "Parts Used",
                "unique_together": {("maintenance_record", "part")},
            },
        ),
    ]
