# Generated by Django 4.2.16 on 2025-06-05 21:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_remove_vehicle_color_remove_vehicle_mileage_and_more"),
        ("maintenance_history", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspection_number", models.CharField(max_length=20, unique=True)),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "inspection_result",
                    models.CharField(
                        choices=[
                            ("PAS", "Passed"),
                            ("PMD", "Passed with minor Defects"),
                            ("PJD", "Passed with major Defects"),
                            ("FMD", "Failed due to minor Defects"),
                            ("FJD", "Failed due to major Defects"),
                            ("FAI", "Failed"),
                        ],
                        max_length=30,
                        verbose_name="Inspection Result",
                    ),
                ),
                ("carfinity_rating", models.CharField(max_length=30)),
                ("inspection_date", models.DateField()),
                ("link_to_results", models.URLField(max_length=400)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
    ]
