# Generated by Django 4.2.16 on 2025-06-20 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance_history", "0002_inspection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerecord",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_maintenance",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Technician",
            ),
        ),
    ]
