# Generated by Django 4.2.16 on 2025-08-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_history", "0003_alter_maintenancerecord_technician"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerecord",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="maintenance_attachments/%Y/%m/%d/",
                verbose_name="Service Receipt/Document",
            ),
        ),
    ]
