# Generated by Django 4.2.16 on 2025-08-14 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_history", "0004_maintenancerecord_attachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancerecord",
            name="attachment",
        ),
    ]
