# Generated by Django 4.2.16 on 2025-08-15 02:43

import django.core.validators
from django.db import migrations, models
import maintenance_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_history", "0005_remove_maintenancerecord_attachment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inspection",
            options={
                "ordering": ["-inspection_date"],
                "verbose_name": "Inspection",
                "verbose_name_plural": "Inspections",
            },
        ),
        migrations.AddField(
            model_name="inspection",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inspection",
            name="inspection_pdf",
            field=models.FileField(
                blank=True,
                help_text="Upload the inspection report as a PDF file",
                null=True,
                upload_to=maintenance_history.models.inspection_pdf_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Inspection Report PDF",
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="pdf_file_size",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="File Size (bytes)"
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="pdf_uploaded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="PDF Upload Date"
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="link_to_results",
            field=models.URLField(
                blank=True,
                max_length=400,
                null=True,
                verbose_name="External Link to Results",
            ),
        ),
    ]
