# Generated by Django 4.2.16 on 2025-08-17 20:38

from django.db import migrations, models
import maintenance_history.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "maintenance_history",
            "0006_alter_inspection_options_inspection_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerecord",
            name="image_description",
            field=models.CharField(
                blank=True,
                help_text="Brief description of what the image shows",
                max_length=255,
                verbose_name="Image Description",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("before", "Before Service"),
                    ("during", "During Service"),
                    ("after", "After Service"),
                    ("parts", "Parts/Components"),
                    ("tools", "Tools Used"),
                    ("damage", "Damage/Issue Found"),
                    ("repair", "Repair Process"),
                    ("completion", "Work Completion"),
                    ("other", "Other"),
                ],
                help_text="Select what type of image this is",
                max_length=20,
                verbose_name="Image Type",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="service_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image as proof of service work performed",
                null=True,
                upload_to=maintenance_history.models.maintenance_image_upload_path,
                verbose_name="Service Image",
            ),
        ),
    ]
