# Generated by Django 4.2.16 on 2025-08-18 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance_history", "0007_maintenancerecord_image_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Inspection Date/Time",
                    ),
                ),
                (
                    "mileage_at_inspection",
                    models.PositiveIntegerField(verbose_name="Vehicle Mileage"),
                ),
                (
                    "engine_oil_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Engine oil level & quality",
                    ),
                ),
                (
                    "oil_filter_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Oil filter condition",
                    ),
                ),
                (
                    "coolant_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Coolant level & leaks",
                    ),
                ),
                (
                    "drive_belts",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Drive belts for cracks/wear",
                    ),
                ),
                (
                    "hoses_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Hoses for leaks or soft spots",
                    ),
                ),
                (
                    "air_filter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Air filter condition",
                    ),
                ),
                (
                    "cabin_air_filter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Cabin air filter condition",
                    ),
                ),
                (
                    "transmission_fluid",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Transmission fluid level & leaks",
                    ),
                ),
                (
                    "engine_mounts",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Engine/transmission mounts",
                    ),
                ),
                (
                    "fluid_leaks",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Fluid leaks under engine & gearbox",
                    ),
                ),
                (
                    "battery_voltage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Battery voltage & charging system",
                    ),
                ),
                (
                    "battery_terminals",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Battery terminals for corrosion",
                    ),
                ),
                (
                    "alternator_output",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Alternator output",
                    ),
                ),
                (
                    "starter_motor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Starter motor performance",
                    ),
                ),
                (
                    "fuses_relays",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="All fuses and relays",
                    ),
                ),
                (
                    "brake_pads",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Brake pads/shoes thickness",
                    ),
                ),
                (
                    "brake_discs",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Brake discs/drums damage/warping",
                    ),
                ),
                (
                    "brake_fluid",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Brake fluid level & condition",
                    ),
                ),
                (
                    "parking_brake",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Parking brake function",
                    ),
                ),
                (
                    "shocks_struts",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Shocks/struts for leaks",
                    ),
                ),
                (
                    "suspension_bushings",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Suspension bushings & joints",
                    ),
                ),
                (
                    "wheel_bearings",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Wheel bearings for noise/play",
                    ),
                ),
                (
                    "steering_response",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Steering response & play",
                    ),
                ),
                (
                    "steering_fluid",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Steering fluid level & leaks",
                    ),
                ),
                (
                    "tire_tread_depth",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name='Tire tread depth (>5/32")',
                    ),
                ),
                (
                    "tire_pressure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Tire pressure (all tires + spare)",
                    ),
                ),
                (
                    "tire_wear_patterns",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Tire wear patterns",
                    ),
                ),
                (
                    "wheels_rims",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Wheels & rims for damage",
                    ),
                ),
                (
                    "exhaust_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Exhaust for leaks/damage",
                    ),
                ),
                (
                    "catalytic_converter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Catalytic converter/muffler condition",
                    ),
                ),
                (
                    "exhaust_warning_lights",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="No exhaust warning lights",
                    ),
                ),
                (
                    "seat_belts",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Seat belts operation & condition",
                    ),
                ),
                (
                    "airbags",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Airbags (warning light off)",
                    ),
                ),
                (
                    "horn_function",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Horn function",
                    ),
                ),
                (
                    "first_aid_kit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="First-aid kit contents",
                    ),
                ),
                (
                    "warning_triangle",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Warning triangle/reflective vest present",
                    ),
                ),
                (
                    "headlights",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Headlights (low/high beam)",
                    ),
                ),
                (
                    "brake_lights",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Brake/reverse/fog lights",
                    ),
                ),
                (
                    "turn_signals",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Turn signals & hazard lights",
                    ),
                ),
                (
                    "interior_lights",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Interior dome/courtesy lights",
                    ),
                ),
                (
                    "windshield",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Windshield for cracks/chips",
                    ),
                ),
                (
                    "wiper_blades",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Wiper blades & washer spray",
                    ),
                ),
                (
                    "rear_defogger",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Rear defogger/heater operation",
                    ),
                ),
                (
                    "mirrors",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Mirrors adjustment & condition",
                    ),
                ),
                (
                    "air_conditioning",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Air conditioning & heating performance",
                    ),
                ),
                (
                    "ventilation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Ventilation airflow",
                    ),
                ),
                (
                    "seat_adjustments",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Seat adjustments & seat heaters",
                    ),
                ),
                (
                    "power_windows",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Power windows & locks",
                    ),
                ),
                (
                    "infotainment_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Infotainment system & Bluetooth/USB",
                    ),
                ),
                (
                    "rear_view_camera",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("na", "Not Applicable"),
                            ("minor", "Minor Issue"),
                            ("major", "Major Issue"),
                        ],
                        max_length=10,
                        verbose_name="Rear-view camera/parking sensors",
                    ),
                ),
                (
                    "engine_notes",
                    models.TextField(
                        blank=True, verbose_name="Engine & Powertrain Notes"
                    ),
                ),
                (
                    "electrical_notes",
                    models.TextField(
                        blank=True, verbose_name="Electrical & Battery Notes"
                    ),
                ),
                (
                    "brakes_notes",
                    models.TextField(
                        blank=True, verbose_name="Brakes & Suspension Notes"
                    ),
                ),
                (
                    "steering_notes",
                    models.TextField(blank=True, verbose_name="Steering & Tires Notes"),
                ),
                (
                    "exhaust_notes",
                    models.TextField(
                        blank=True, verbose_name="Exhaust & Emissions Notes"
                    ),
                ),
                (
                    "safety_notes",
                    models.TextField(blank=True, verbose_name="Safety Equipment Notes"),
                ),
                (
                    "lighting_notes",
                    models.TextField(
                        blank=True, verbose_name="Lighting & Visibility Notes"
                    ),
                ),
                (
                    "hvac_notes",
                    models.TextField(blank=True, verbose_name="HVAC & Interior Notes"),
                ),
                (
                    "technology_notes",
                    models.TextField(
                        blank=True, verbose_name="Technology & Driver Assist Notes"
                    ),
                ),
                (
                    "overall_notes",
                    models.TextField(
                        blank=True, verbose_name="Overall Inspection Notes"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        verbose_name="Recommendations for Future Maintenance",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, verbose_name="Inspection Form Completed"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completion Date/Time"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections_form",
                        to="maintenance_history.inspection",
                        verbose_name="Related Inspection",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections_forms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Inspecting Technician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspections",
                "verbose_name_plural": "Inspections",
                "ordering": ["-inspection_date"],
            },
        ),
    ]
