# Generated by Django 4.2.16 on 2025-08-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_history", "0008_inspections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspection",
            name="carfinity_rating",
        ),
        migrations.AddField(
            model_name="inspection",
            name="vehicle_health_index",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Vehicle Health Index"
            ),
        ),
    ]
