# Generated by Django 4.2.16 on 2025-10-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_history", "0010_alter_inspections_options_initialinspection"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerecord",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total cost of the maintenance service",
                max_digits=10,
                null=True,
                verbose_name="Total Service Cost",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="parts_replaced",
            field=models.TextField(
                blank=True,
                help_text="List of parts that were replaced during service",
                verbose_name="Parts Replaced",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="service_provider",
            field=models.CharField(
                blank=True,
                help_text="Name of the service provider or garage",
                max_length=255,
                verbose_name="Service Provider",
            ),
        ),
    ]
