# Generated by Django 4.2.16 on 2025-06-07 19:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0004_remove_vehicle_color_remove_vehicle_mileage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PowertrainAndDrivetrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_engine",
                    models.CharField(
                        blank=True,
                        help_text="Type and specifications of the base engine (e.g., '2.0L Turbo I4')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "engine_displacement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Engine displacement in liters",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "engine_power",
                    models.PositiveIntegerField(
                        blank=True, help_text="Engine power in horsepower", null=True
                    ),
                ),
                (
                    "transmission_specifications",
                    models.CharField(
                        blank=True,
                        help_text="Detailed transmission specifications",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "transmission_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MT", "Manual Transmission"),
                            ("AT", "Automatic Transmission"),
                            ("CVT", "Continuously Variable Transmission"),
                            ("DCT", "Dual-Clutch Transmission"),
                            ("AMT", "Automated Manual Transmission"),
                        ],
                        help_text="Type of transmission system",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "gear_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Number of gears",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "drive_layout",
                    models.CharField(
                        choices=[
                            ("FWD", "Front-Wheel Drive"),
                            ("RWD", "Rear-Wheel Drive"),
                            ("AWD", "All-Wheel Drive"),
                            ("4WD", "Four-Wheel Drive"),
                        ],
                        help_text="Vehicle's drive configuration",
                        max_length=3,
                    ),
                ),
                (
                    "fuel_system",
                    models.CharField(
                        choices=[
                            ("G", "Gasoline"),
                            ("D", "Diesel"),
                            ("E", "Electric"),
                            ("H", "Hybrid"),
                            ("P", "Plug-in Hybrid"),
                            ("F", "Fuel Cell"),
                        ],
                        help_text="Type of fuel system",
                        max_length=1,
                    ),
                ),
                (
                    "emissions_standard",
                    models.CharField(
                        choices=[
                            ("EU1", "Euro 1"),
                            ("EU2", "Euro 2"),
                            ("EU3", "Euro 3"),
                            ("EU4", "Euro 4"),
                            ("EU5", "Euro 5"),
                            ("EU6", "Euro 6"),
                            ("EPA1", "EPA Tier 1"),
                        ],
                        help_text="Vehicle emissions standard compliance",
                        max_length=4,
                    ),
                ),
                (
                    "has_start_stop",
                    models.BooleanField(
                        default=False, help_text="Has automatic start-stop system"
                    ),
                ),
                (
                    "has_regenerative_braking",
                    models.BooleanField(
                        default=False, help_text="Has regenerative braking system"
                    ),
                ),
                (
                    "gearshift_position",
                    models.CharField(
                        choices=[
                            ("C", "Center Console"),
                            ("S", "Steering Column"),
                            ("D", "Dashboard"),
                        ],
                        help_text="Location of gearshift mechanism",
                        max_length=1,
                    ),
                ),
                (
                    "gearshift_material",
                    models.CharField(
                        blank=True,
                        help_text="Material of gearshift knob/handle (e.g., 'Leather-wrapped')",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional powertrain notes or special features",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Powertrain & Drivetrain",
                "verbose_name_plural": "Powertrain & Drivetrain Systems",
                "ordering": ["base_engine"],
            },
        ),
    ]
