# Generated by Django 4.2.16 on 2025-05-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataconsent",
            name="consent_type",
            field=models.CharField(
                choices=[
                    ("PRIVACY", "Privacy Policy"),
                    ("EMAIL", "Email Notifications"),
                    ("DATA", "Data Collection"),
                    ("DATA_ANALYTICS", "Data Usage Analytics and Service Improvement"),
                ],
                help_text="Type of consent (e.g., 'privacy_policy', 'email_notifications').",
                max_length=100,
            ),
        ),
    ]
