# Generated by Django 4.2.16 on 2025-06-20 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0006_alter_vehiclehistory_reported_by_and_more"),
        ("maintenance", "0008_alter_assignedvehicleplan_owner_and_more"),
        ("maintenance_history", "0003_alter_maintenancerecord_technician"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0003_alter_organizationuser_user_and_more"),
        ("users", "0002_alter_dataconsent_consent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataconsent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_consents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_organization_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
