# Generated by Django 4.2.16 on 2025-09-20 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0003_alter_dataconsent_user_alter_organizationuser_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[
                            ("customer", "Customer Dashboard"),
                            ("insurance", "Insurance Dashboard"),
                            ("admin", "Admin Dashboard"),
                            ("technician", "Technician Dashboard"),
                            ("custom", "Custom Dashboard"),
                        ],
                        help_text="Type of dashboard this group provides access to",
                        max_length=20,
                    ),
                ),
                (
                    "dashboard_url",
                    models.CharField(
                        help_text="URL path for the dashboard (e.g., '/dashboard/', '/insurance/')",
                        max_length=200,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for this group (e.g., 'Customer Users', 'Insurance Agents')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this group provides access to",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="Priority when user has multiple groups (higher number = default dashboard)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this group configuration is active",
                    ),
                ),
                (
                    "compatible_org_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of organization types compatible with this group (e.g., ['insurance', 'fleet'])",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        help_text="Django group that this configuration applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_config",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authentication Group Configuration",
                "verbose_name_plural": "Authentication Group Configurations",
                "ordering": ["-priority", "display_name"],
            },
        ),
    ]
