# Generated by Django 4.2.16 on 2025-10-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_authenticationgroup"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthenticationGroup",
        ),
    ]
