#databases:
#  - name: carfinity-django-render
#    plan: free
#    databaseName: carfinity_django_render
#    user: carfinity_django_render_user

services:
  - type: web
    plan: free
    name: carfinity
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn carfinity.asgi:application -k uvicorn.workers.UvicornWorker'
    #envVars:
    #  - key: DATABASE_URL
    #    fromDatabase:
    #      name: carfinity-django-render
    #      property: connectionString
    #  - key: SECRET_KEY
    #    generateValue: true
    #  - key: WEB_CONCURRENCY
    #    value: 4