# Generated by Django 4.2.16 on 2025-08-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_alter_organizationuser_user_and_more"),
        ("insurance_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancepolicy",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Insurance company providing this policy",
                limit_choices_to={"is_insurance_provider": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insurance_policies",
                to="organizations.organization",
            ),
        ),
    ]
