# Generated by Django 4.2.16 on 2025-08-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0009_part_category_part_minimum_stock_level_and_more"),
        ("insurance_app", "0005_change_scheduled_maintenance_to_foreignkey"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintenanceschedule",
            options={"ordering": ["scheduled_date", "priority_level"]},
        ),
        migrations.AddField(
            model_name="maintenanceschedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="maintenanceschedule",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceschedule",
            name="due_mileage",
            field=models.PositiveIntegerField(
                blank=True, help_text="Mileage when maintenance is due", null=True
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceschedule",
            name="maintenance_type",
            field=models.CharField(
                choices=[
                    ("oil_change", "Oil Change"),
                    ("brake_service", "Brake Service"),
                    ("tire_rotation", "Tire Rotation"),
                    ("transmission_service", "Transmission Service"),
                    ("engine_tune_up", "Engine Tune-up"),
                    ("air_filter", "Air Filter Replacement"),
                    ("coolant_flush", "Coolant Flush"),
                    ("battery_service", "Battery Service"),
                    ("inspection", "Safety Inspection"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceschedule",
            name="priority_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceschedule",
            name="scheduled_maintenance",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to scheduled maintenance in maintenance app",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="insurance_schedules",
                to="maintenance.scheduledmaintenance",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenanceschedule",
            index=models.Index(
                fields=["scheduled_date", "is_completed"],
                name="insurance_a_schedul_7178e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenanceschedule",
            index=models.Index(
                fields=["vehicle", "maintenance_type"],
                name="insurance_a_vehicle_9af6fd_idx",
            ),
        ),
    ]
