# Generated by Django 4.2.16 on 2025-10-05 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessments", "0002_agentassignment_alter_assessmentphoto_options_and_more"),
        ("insurance_app", "0006_alter_maintenanceschedule_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Change"),
                            ("cost_adjustment", "Cost Adjustment"),
                            ("document_update", "Document Update"),
                            ("agent_assignment", "Agent Assignment"),
                            ("comment_added", "Comment Added"),
                            ("photo_uploaded", "Photo Uploaded"),
                            ("photo_deleted", "Photo Deleted"),
                            ("section_updated", "Section Updated"),
                            ("workflow_action", "Workflow Action"),
                            ("report_generated", "Report Generated"),
                            ("approval_granted", "Approval Granted"),
                            ("rejection_issued", "Rejection Issued"),
                            ("changes_requested", "Changes Requested"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "field_name",
                    models.CharField(
                        blank=True, help_text="Field that was changed", max_length=100
                    ),
                ),
                ("old_value", models.TextField(blank=True, help_text="Previous value")),
                ("new_value", models.TextField(blank=True, help_text="New value")),
                (
                    "description",
                    models.TextField(help_text="Description of the activity"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or context"
                    ),
                ),
                (
                    "related_comment_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "related_photo_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("related_section", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="assessments.vehicleassessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment_data",
                    models.JSONField(help_text="Complete snapshot of assessment data"),
                ),
                (
                    "change_summary",
                    models.TextField(help_text="Summary of changes in this version"),
                ),
                (
                    "is_major_version",
                    models.BooleanField(
                        default=False, help_text="Major version change"
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="assessments.vehicleassessment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_snapshot",
                        to="insurance_app.assessmenthistory",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "indexes": [
                    models.Index(
                        fields=["assessment", "version_number"],
                        name="insurance_a_assessm_abaafc_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="insurance_a_created_d8113f_idx"
                    ),
                ],
                "unique_together": {("assessment", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="AssessmentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Change"),
                            ("comment_added", "Comment Added"),
                            ("deadline_reminder", "Deadline Reminder"),
                            ("approval_required", "Approval Required"),
                            ("rejection_notice", "Rejection Notice"),
                            ("changes_requested", "Changes Requested"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Unread"),
                            ("read", "Read"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="unread",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_notifications",
                        to="assessments.vehicleassessment",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_assessment_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.assessmentcomment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status", "created_at"],
                        name="insurance_a_recipie_823a4e_idx",
                    ),
                    models.Index(
                        fields=["assessment", "created_at"],
                        name="insurance_a_assessm_d86306_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="assessmenthistory",
            index=models.Index(
                fields=["assessment", "timestamp"],
                name="insurance_a_assessm_7779ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmenthistory",
            index=models.Index(
                fields=["activity_type", "timestamp"],
                name="insurance_a_activit_2cbaea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmenthistory",
            index=models.Index(
                fields=["user", "timestamp"], name="insurance_a_user_id_a84fe2_idx"
            ),
        ),
    ]
