# Generated by Django 4.2.16 on 2025-11-05 03:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "assessments",
            "0004_vehicleassessment_parts_identification_complete_and_more",
        ),
        ("insurance_app", "0007_assessmenthistory_assessmentversion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DamagedPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("exterior", "Exterior"),
                            ("mechanical", "Mechanical"),
                            ("interior", "Interior"),
                            ("electrical", "Electrical"),
                            ("wheels", "Wheels"),
                            ("safety", "Safety"),
                            ("structural", "Structural"),
                            ("fluids", "Fluids"),
                        ],
                        max_length=20,
                    ),
                ),
                ("part_name", models.CharField(max_length=200)),
                (
                    "part_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "part_category",
                    models.CharField(
                        choices=[
                            ("body", "Body Panel"),
                            ("mechanical", "Mechanical Component"),
                            ("electrical", "Electrical Component"),
                            ("glass", "Glass/Windows"),
                            ("interior", "Interior Component"),
                            ("trim", "Trim/Cosmetic"),
                            ("wheels", "Wheels/Tires"),
                            ("safety", "Safety System"),
                            ("structural", "Structural Component"),
                            ("fluid", "Fluid System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "damage_severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor Damage"),
                            ("moderate", "Moderate Damage"),
                            ("severe", "Severe Damage"),
                            ("replace", "Requires Replacement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("damage_description", models.TextField()),
                ("requires_replacement", models.BooleanField(default=False)),
                (
                    "estimated_labor_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("identified_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damaged_parts",
                        to="assessments.vehicleassessment",
                    ),
                ),
                (
                    "damage_images",
                    models.ManyToManyField(
                        blank=True, to="assessments.assessmentphoto"
                    ),
                ),
            ],
            options={
                "ordering": ["section_type", "part_category", "part_name"],
            },
        ),
        migrations.CreateModel(
            name="PartQuoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("sent", "Sent to Provider"),
                            ("received", "Quote Received"),
                            ("expired", "Request Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("include_assessor", models.BooleanField(default=False)),
                ("include_dealer", models.BooleanField(default=False)),
                ("include_independent", models.BooleanField(default=False)),
                ("include_network", models.BooleanField(default=False)),
                ("vehicle_make", models.CharField(max_length=100)),
                ("vehicle_model", models.CharField(max_length=100)),
                ("vehicle_year", models.IntegerField()),
                ("vehicle_vin", models.CharField(blank=True, max_length=17)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_quote_requests",
                        to="assessments.vehicleassessment",
                    ),
                ),
                (
                    "damaged_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_requests",
                        to="insurance_app.damagedpart",
                    ),
                ),
                (
                    "dispatched_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="PartQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("assessor", "Assessor Estimate"),
                            ("dealer", "Authorized Dealer"),
                            ("independent", "Independent Garage"),
                            ("network", "Insurance Network"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_name", models.CharField(max_length=200)),
                ("provider_contact", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("validated", "Validated"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("part_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("labor_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "paint_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "additional_costs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "part_type",
                    models.CharField(
                        choices=[
                            ("oem", "OEM (Original Equipment)"),
                            ("oem_equivalent", "OEM Equivalent"),
                            ("aftermarket", "Aftermarket"),
                            ("used", "Used/Reconditioned"),
                        ],
                        default="oem",
                        max_length=50,
                    ),
                ),
                ("part_manufacturer", models.CharField(blank=True, max_length=100)),
                ("part_number_quoted", models.CharField(blank=True, max_length=100)),
                ("estimated_delivery_days", models.IntegerField()),
                ("estimated_completion_days", models.IntegerField()),
                ("part_warranty_months", models.IntegerField(default=12)),
                ("labor_warranty_months", models.IntegerField(default=12)),
                (
                    "confidence_score",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("quote_date", models.DateTimeField(auto_now_add=True)),
                ("valid_until", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                (
                    "damaged_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="insurance_app.damagedpart",
                    ),
                ),
                (
                    "quote_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="insurance_app.partquoterequest",
                    ),
                ),
            ],
            options={
                "ordering": ["total_cost"],
            },
        ),
        migrations.CreateModel(
            name="PartMarketAverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "average_total_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "average_part_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "average_labor_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "min_total_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "max_total_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "standard_deviation",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "variance_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("quote_count", models.IntegerField()),
                (
                    "confidence_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("outlier_quotes", models.JSONField(blank=True, default=list)),
                ("calculated_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "damaged_part",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_average",
                        to="insurance_app.damagedpart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentQuoteSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("collecting", "Collecting Quotes"),
                            ("analysis", "Analyzing Quotes"),
                            ("ready", "Ready for Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="collecting",
                        max_length=20,
                    ),
                ),
                ("total_parts_identified", models.IntegerField(default=0)),
                ("parts_with_quotes", models.IntegerField(default=0)),
                ("total_quote_requests", models.IntegerField(default=0)),
                ("quotes_received", models.IntegerField(default=0)),
                (
                    "assessor_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "dealer_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "independent_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "network_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "market_average_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "recommended_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "potential_savings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "recommended_provider_mix",
                    models.JSONField(blank=True, default=dict),
                ),
                ("recommendation_reasoning", models.TextField(blank=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_summary",
                        to="assessments.vehicleassessment",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_quote_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Assessment Quote Summaries",
            },
        ),
        migrations.CreateModel(
            name="VehicleAssessmentQuoteExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_extension",
                        to="assessments.vehicleassessment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["assessment"], name="insurance_a_assessm_8bc917_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="partquoterequest",
            index=models.Index(
                fields=["request_id"], name="insurance_a_request_74381e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partquoterequest",
            index=models.Index(
                fields=["assessment", "status"], name="insurance_a_assessm_8aec3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partquoterequest",
            index=models.Index(
                fields=["expiry_date", "status"], name="insurance_a_expiry__2e31b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partquoterequest",
            index=models.Index(
                fields=["dispatched_by", "request_date"],
                name="insurance_a_dispatc_8adf7a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partquote",
            index=models.Index(
                fields=["quote_request", "provider_type"],
                name="insurance_a_quote_r_0af952_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partquote",
            index=models.Index(
                fields=["damaged_part", "total_cost"],
                name="insurance_a_damaged_4b0a96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partquote",
            index=models.Index(
                fields=["quote_date"], name="insurance_a_quote_d_f1cd39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partquote",
            index=models.Index(
                fields=["valid_until", "status"], name="insurance_a_valid_u_5df820_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partmarketaverage",
            index=models.Index(
                fields=["damaged_part"], name="insurance_a_damaged_9f2cde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partmarketaverage",
            index=models.Index(
                fields=["calculated_date"], name="insurance_a_calcula_bff8a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partmarketaverage",
            index=models.Index(
                fields=["confidence_level"], name="insurance_a_confide_3f0139_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="damagedpart",
            index=models.Index(
                fields=["assessment", "section_type"],
                name="insurance_a_assessm_7e455f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="damagedpart",
            index=models.Index(
                fields=["part_category", "damage_severity"],
                name="insurance_a_part_ca_7ac733_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="damagedpart",
            index=models.Index(
                fields=["identified_date"], name="insurance_a_identif_4edddb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentquotesummary",
            index=models.Index(
                fields=["assessment"], name="insurance_a_assessm_08bf5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentquotesummary",
            index=models.Index(
                fields=["status", "last_updated"], name="insurance_a_status_119ea9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentquotesummary",
            index=models.Index(
                fields=["created_date"], name="insurance_a_created_c007a1_idx"
            ),
        ),
    ]
