# Generated by Django 4.2.16 on 2025-11-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_app", "0008_damagedpart_partquoterequest_partquote_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VehicleAssessmentQuoteExtension",
        ),
    ]
