# Generated by Django 4.2.16 on 2025-10-05 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary_reviewer", "Primary Reviewer"),
                            ("secondary_reviewer", "Secondary Reviewer"),
                            ("specialist", "Specialist"),
                            ("supervisor", "Supervisor"),
                            ("final_approver", "Final Approver"),
                        ],
                        default="primary_reviewer",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("reassigned", "Reassigned"),
                            ("declined", "Declined"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                ("accepted_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-assigned_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="assessmentphoto",
            options={
                "ordering": ["section_reference", "is_primary", "category", "taken_at"]
            },
        ),
        migrations.AddField(
            model_name="assessmentphoto",
            name="damage_point_id",
            field=models.CharField(
                blank=True,
                help_text="Specific damage location reference (e.g., 'front_bumper', 'driver_side_door')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assessmentphoto",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this is the main photo for the assessment section",
            ),
        ),
        migrations.AddField(
            model_name="assessmentphoto",
            name="section_reference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exterior_damage", "Exterior Body Damage"),
                    ("wheels_tires", "Wheels and Tires"),
                    ("interior_damage", "Interior Damage"),
                    ("mechanical_systems", "Mechanical Systems"),
                    ("electrical_systems", "Electrical Systems"),
                    ("safety_systems", "Safety Systems"),
                    ("frame_structural", "Frame and Structural"),
                    ("fluid_systems", "Fluid Systems"),
                    ("documentation", "Documentation and Identification"),
                    ("overall", "Overall Vehicle"),
                ],
                help_text="Links photo to specific assessment section",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicleassessment",
            name="agent_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes and comments from the assigned insurance agent",
            ),
        ),
        migrations.AddField(
            model_name="vehicleassessment",
            name="agent_status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Review"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("changes_requested", "Changes Requested"),
                    ("on_hold", "On Hold"),
                ],
                default="pending_review",
                help_text="Current status of agent review process",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicleassessment",
            name="assigned_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Insurance agent assigned to review this assessment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicleassessment",
            name="review_deadline",
            field=models.DateTimeField(
                blank=True, help_text="Deadline for agent review completion", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentphoto",
            index=models.Index(
                fields=["assessment", "section_reference"],
                name="assessments_assessm_516c66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentphoto",
            index=models.Index(
                fields=["section_reference", "is_primary"],
                name="assessments_section_399731_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentphoto",
            index=models.Index(
                fields=["damage_point_id"], name="assessments_damage__8df850_idx"
            ),
        ),
        migrations.AddField(
            model_name="agentassignment",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentassignment",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_assignments",
                to="assessments.vehicleassessment",
            ),
        ),
        migrations.AddField(
            model_name="agentassignment",
            name="assigned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="agentassignment",
            index=models.Index(
                fields=["agent", "status"], name="assessments_agent_i_28c0be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentassignment",
            index=models.Index(
                fields=["assessment", "is_primary"],
                name="assessments_assessm_dc471e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentassignment",
            unique_together={("agent", "assessment", "role")},
        ),
    ]
