# Generated by Django 4.2.16 on 2025-10-08 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_organization_insurance_license_number_and_more"),
        ("assessments", "0002_agentassignment_alter_assessmentphoto_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleassessment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this assessment is being conducted for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="organizations.organization",
            ),
        ),
    ]
