# Generated by Django 4.2.16 on 2025-11-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_vehicleassessment_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleassessment",
            name="parts_identification_complete",
            field=models.BooleanField(
                default=False,
                help_text="Whether damaged parts have been identified and processed",
            ),
        ),
        migrations.AddField(
            model_name="vehicleassessment",
            name="quote_collection_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="not_started",
                help_text="Current status of quote collection process",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicleassessment",
            name="uses_parts_based_quotes",
            field=models.BooleanField(
                default=True,
                help_text="Whether this assessment uses parts-based quotes (True) or hardcoded costs (False)",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentphoto",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("overall", "Overall Vehicle"),
                    ("damage", "Damage Detail"),
                    ("interior", "Interior"),
                    ("engine", "Engine Bay"),
                    ("undercarriage", "Undercarriage"),
                    ("documents", "Documentation"),
                    ("vin", "VIN Plate"),
                    ("odometer", "Odometer Reading"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="assessmentphoto",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="assessment_photos/%Y/%m/%d/"
            ),
        ),
    ]
