# Generated by Django 4.2.16 on 2025-05-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
        ("organizations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationvehicle",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_vehicles",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="organizationvehicle",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_vehicles",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationvehicle",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_vehicles",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_members",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_organization_users",
                to="users.user",
            ),
        ),
    ]
