# Generated by Django 4.2.16 on 2025-08-17 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0003_alter_organizationuser_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="insurance_license_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="insurance_rating",
            field=models.CharField(
                blank=True,
                help_text="A.M. Best rating or similar",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_insurance_provider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="linked_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Django groups linked to this organization for permission management",
                related_name="organizations",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("insurance", "Insurance Company"),
                    ("fleet", "Fleet Management"),
                    ("dealership", "Dealership"),
                    ("service", "Service Provider"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MANAGER", "Manager"),
                    ("DRIVER", "Driver"),
                    ("AGENT", "Insurance Agent"),
                    ("UNDERWRITER", "Underwriter"),
                    ("CLAIMS_ADJUSTER", "Claims Adjuster"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationuser",
            unique_together={("user", "organization")},
        ),
        migrations.CreateModel(
            name="InsuranceOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naic_number",
                    models.CharField(
                        blank=True,
                        help_text="NAIC Company Code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "am_best_rating",
                    models.CharField(
                        blank=True,
                        help_text="A.M. Best Financial Strength Rating",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "states_licensed",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of states where licensed",
                    ),
                ),
                ("total_policies", models.IntegerField(default=0)),
                (
                    "total_premium_volume",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "max_risk_score_threshold",
                    models.FloatField(
                        default=7.0, help_text="Maximum acceptable risk score"
                    ),
                ),
                ("auto_approve_low_risk", models.BooleanField(default=True)),
                (
                    "require_inspection_threshold",
                    models.FloatField(
                        default=5.0,
                        help_text="Risk score requiring mandatory inspection",
                    ),
                ),
                ("send_maintenance_alerts", models.BooleanField(default=True)),
                ("send_risk_alerts", models.BooleanField(default=True)),
                (
                    "alert_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_details",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
