# Generated by Django 4.2.16 on 2025-05-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceschedule",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_schedules",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecordpart",
            name="maintenance_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts_used",
                to="maintenance.maintenancerecord",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecordpart",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_records",
                to="maintenance.part",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="maintenance.servicetype",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_records",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="maintenance_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="maintenance.maintenancerecord",
            ),
        ),
    ]
