# Generated by Django 4.2.16 on 2025-05-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_dataconsent_consent_type"),
        ("vehicles", "0002_alter_vehiclehistory_vehicle"),
        ("maintenance", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenancePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="E.g., 'Premium Service Package'", max_length=100
                    ),
                ),
                (
                    "vehicle_model",
                    models.CharField(
                        help_text="E.g., 'Toyota Camry 2023'", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "interval_miles",
                    models.PositiveIntegerField(
                        help_text="Mileage interval (e.g., 5000)"
                    ),
                ),
                (
                    "interval_months",
                    models.PositiveIntegerField(
                        help_text="Time interval in months (e.g., 6)"
                    ),
                ),
                (
                    "estimated_time",
                    models.DurationField(help_text="Estimated duration (HH:MM:SS)"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "interval_miles"],
            },
        ),
        migrations.CreateModel(
            name="TaskPartRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.part",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.maintenancetask",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="parts",
            field=models.ManyToManyField(
                blank=True,
                through="maintenance.TaskPartRequirement",
                to="maintenance.part",
            ),
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="maintenance.maintenanceplan",
            ),
        ),
        migrations.CreateModel(
            name="AssignedVehiclePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "current_mileage",
                    models.PositiveIntegerField(help_text="Mileage at assignment"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="maintenance.maintenanceplan",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_plans",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                ("due_mileage", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("OVERDUE", "Overdue"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "completed_mileage",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="maintenance.assignedvehicleplan",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.maintenancetask",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services_performed",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
                "indexes": [
                    models.Index(
                        fields=["due_date", "status"],
                        name="maintenance_due_dat_4398a3_idx",
                    )
                ],
            },
        ),
    ]
