# Generated by Django 4.2.16 on 2025-05-27 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "maintenance",
            "0003_maintenanceplan_maintenancetask_taskpartrequirement_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancerecordpart",
            name="maintenance_record",
        ),
        migrations.RemoveField(
            model_name="maintenancerecordpart",
            name="part",
        ),
        migrations.RemoveField(
            model_name="maintenanceschedule",
            name="service_type",
        ),
        migrations.RemoveField(
            model_name="maintenanceschedule",
            name="vehicle",
        ),
        migrations.AlterField(
            model_name="document",
            name="maintenance_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="maintenance.scheduledmaintenance",
            ),
        ),
        migrations.DeleteModel(
            name="MaintenanceRecord",
        ),
        migrations.DeleteModel(
            name="MaintenanceRecordPart",
        ),
        migrations.DeleteModel(
            name="MaintenanceSchedule",
        ),
    ]
