# Generated by Django 4.2.16 on 2025-05-28 08:08

from django.db import migrations, models
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "maintenance",
            "0004_remove_maintenancerecordpart_maintenance_record_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancetask",
            name="service_type",
            field=models.CharField(
                default=1,
                help_text="Type of service",
                max_length=100,
                verbose_name=maintenance.models.ServiceType,
            ),
            preserve_default=False,
        ),
    ]
