# Generated by Django 4.2.16 on 2025-05-28 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0005_maintenancetask_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancetask",
            name="service_type",
            field=models.ForeignKey(
                help_text="Type of service",
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="maintenance.servicetype",
            ),
        ),
    ]
