# Generated by Django 4.2.16 on 2025-05-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0006_alter_maintenancetask_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenanceplan",
            name="name",
            field=models.CharField(
                help_text="E.g., 'Toyota 1uz Gasoline Service Plan'", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="name",
            field=models.CharField(
                help_text="Oil Change, Air Filter Fitting", max_length=100
            ),
        ),
    ]
