# Generated by Django 4.2.16 on 2025-06-20 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0007_alter_maintenanceplan_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignedvehicleplan",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="scheduledmaintenance",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
