# Generated by Django 4.2.16 on 2025-08-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0008_alter_assignedvehicleplan_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="part",
            name="minimum_stock_level",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="part",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
