# Generated by Django 4.2.16 on 2025-05-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_alter_vehiclehistory_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclehistory",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="vehiclehistory",
            name="event_date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="vehiclehistory",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACCIDENT", "Accident"),
                    ("ODOMETER_FRAUD", "Odometer Fraud"),
                    ("THEFT", "Theft"),
                    ("RECALL", "Recall"),
                    ("REPAIR", "Repair"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
