# Generated by Django 4.2.16 on 2025-06-05 21:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0003_alter_vehiclehistory_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="color",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="mileage",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="exterior_color",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="interior_color",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="powertrain_power",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.CreateModel(
            name="VehicleStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accident_history",
                    models.CharField(
                        choices=[
                            ("NHA", "No History of Accidents"),
                            ("OIIA", "Once Involved In Accident"),
                            ("CAD", "Currently Accident Damaged"),
                        ],
                        default="NHA",
                        help_text="History of accidents involving the vehicle",
                        max_length=30,
                    ),
                ),
                (
                    "odometer_fraud",
                    models.CharField(
                        choices=[
                            ("NOF", "No Odometer Fraud"),
                            ("SOF", "Suspected Odometer Fraud"),
                        ],
                        default="NOF",
                        help_text="Indicates if the vehicle has suspected odometer fraud",
                        max_length=30,
                    ),
                ),
                (
                    "theft_involvement",
                    models.CharField(
                        choices=[
                            ("NHT", "No History of Theft"),
                            ("OIT", "Once Involved In Theft"),
                            ("STI", "Suspected Theft Involvement"),
                        ],
                        default="NHT",
                        help_text="Indicates if the vehicle has been involved in theft",
                        max_length=30,
                    ),
                ),
                (
                    "legal_status",
                    models.CharField(
                        choices=[
                            ("LG", "Looks Good"),
                            ("ILA", "Involved Legal Action"),
                        ],
                        default="LG",
                        help_text="Indicates if the vehicle is involved in any legal action or attached to bank",
                        max_length=30,
                    ),
                ),
                (
                    "owner_history",
                    models.IntegerField(
                        default=0,
                        help_text="Number of previous owners of the vehicle",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "vehicle",
                    models.OneToOneField(
                        help_text="Vehicle Identification Number",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehiclestatus",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Status",
                "verbose_name_plural": "Vehicle Statuses",
            },
        ),
    ]
