# Generated by Django 4.2.16 on 2025-06-17 11:36

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_remove_vehicle_color_remove_vehicle_mileage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="body_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="plant_location",
            field=django_countries.fields.CountryField(
                blank=True, max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="powertrain_displacement",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
