# Generated by Django 4.2.16 on 2025-08-08 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vehicles", "0006_alter_vehiclehistory_reported_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="vehicle_images/")),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("FRONT", "Front View"),
                            ("REAR", "Rear View"),
                            ("SIDE_LEFT", "Left Side"),
                            ("SIDE_RIGHT", "Right Side"),
                            ("INTERIOR", "Interior"),
                            ("ENGINE", "Engine Bay"),
                            ("DASHBOARD", "Dashboard"),
                            ("TRUNK", "Trunk/Cargo Area"),
                            ("WHEELS", "Wheels/Tires"),
                            ("DAMAGE", "Damage/Issues"),
                            ("DOCUMENTS", "Documents"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Mark as primary image for the vehicle"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_vehicle_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Image",
                "verbose_name_plural": "Vehicle Images",
                "ordering": ["-is_primary", "-uploaded_at"],
            },
        ),
    ]
