# Generated by Django 4.2.16 on 2025-08-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0007_vehicleimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="plant_location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
