# Generated by Django 4.2.16 on 2025-10-05 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0008_alter_vehicle_plant_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleValuation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated market value in local currency",
                        max_digits=10,
                    ),
                ),
                (
                    "condition_rating",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("very_good", "Very Good"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        help_text="Overall condition rating of the vehicle",
                        max_length=20,
                    ),
                ),
                (
                    "valuation_source",
                    models.CharField(
                        choices=[
                            ("kbb", "Kelley Blue Book"),
                            ("edmunds", "Edmunds"),
                            ("nada", "NADA Guides"),
                            ("autotrader", "AutoTrader"),
                            ("cargurus", "CarGurus"),
                            ("manual", "Manual Assessment"),
                            ("insurance", "Insurance Appraisal"),
                            ("dealer", "Dealer Assessment"),
                        ],
                        help_text="Source of the valuation data",
                        max_length=20,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this valuation was last updated"
                    ),
                ),
                (
                    "mileage_at_valuation",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Vehicle mileage when valuation was performed",
                        null=True,
                    ),
                ),
                (
                    "valuation_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the valuation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.OneToOneField(
                        help_text="Vehicle this valuation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuation",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Valuation",
                "verbose_name_plural": "Vehicle Valuations",
                "ordering": ["-last_updated"],
            },
        ),
    ]
