# Generated by Django 4.2.16 on 2025-08-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingvehicleonboarding",
            name="image_data",
            field=models.JSONField(
                blank=True, help_text="Stores image URLs and metadata", null=True
            ),
        ),
    ]
