# Generated by Django 4.2.16 on 2025-10-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0009_vehiclevaluation"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("MAINTENANCE_OVERDUE", "Maintenance Overdue"),
                            ("PART_REPLACEMENT", "Part Replacement"),
                            ("INSURANCE_EXPIRY", "Insurance Expiry"),
                            ("INSPECTION_DUE", "Inspection Due"),
                        ],
                        help_text="Type of alert",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        help_text="Priority level of the alert",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Alert title/summary", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the alert"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this alert is currently active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this alert was created"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When this alert was resolved", null=True
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="Vehicle this alert belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Alert",
                "verbose_name_plural": "Vehicle Alerts",
                "ordering": ["-created_at", "-priority"],
            },
        ),
        migrations.CreateModel(
            name="VehicleCostAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="Month for which these analytics are calculated (first day of month)"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost for the month",
                        max_digits=10,
                    ),
                ),
                (
                    "maintenance_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total maintenance cost for the month",
                        max_digits=10,
                    ),
                ),
                (
                    "parts_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total parts cost for the month",
                        max_digits=10,
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total labor cost for the month",
                        max_digits=10,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="Vehicle this cost analytics belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_analytics",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Cost Analytics",
                "verbose_name_plural": "Vehicle Cost Analytics",
                "ordering": ["-month"],
                "unique_together": {("vehicle", "month")},
            },
        ),
    ]
