# Generated by Django 4.2.16 on 2025-10-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_add_database_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="vehiclealert",
            index=models.Index(
                fields=["vehicle", "is_active"], name="notificatio_vehicle_d29dfd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclealert",
            index=models.Index(
                fields=["vehicle", "alert_type", "is_active"],
                name="notificatio_vehicle_0093a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclealert",
            index=models.Index(
                fields=["priority", "created_at"], name="notificatio_priorit_267fcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclealert",
            index=models.Index(
                fields=["is_active", "created_at"],
                name="notificatio_is_acti_b13f34_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclecostanalytics",
            index=models.Index(
                fields=["vehicle", "month"], name="notificatio_vehicle_29dde2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclecostanalytics",
            index=models.Index(fields=["month"], name="notificatio_month_3dbddb_idx"),
        ),
    ]
